x = 2
#defines a local variable (x), evaluates to => 2
puts x = 2
#prints "2", evaluates to => nil (this will output the argument, but not return anything)
p name = "Joe"
#"prints "Joe"", evaluates to => "Joe" (p will output the argument AND return the argument)
four = "four"
#defines local variable (four), evaluates to => 4
print something = "nothing"
#prints nothing, evaluates to => nil (print method does not append new line onto its output)